# Generated by Django 4.2.7 on 2024-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['level', 'name'], 'verbose_name': 'пункт меню', 'verbose_name_plural': 'пункты меню'},
        ),
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='уровень'),
            preserve_default=False,
        ),
    ]
